# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:     
  testAndPublish:
    runs-on: self-hosted
    steps:
    #- name: delete database
     # run: rm ~/data/test.mv.db ~/data/test.trace.db 
    - uses: actions/checkout@v2
    - name: setup java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        architecture: arm
        cache: maven
    - name: build artifact
      run: mvn clean package
    - name: deploy site
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages
        folder: src/frontend/dist
